project_id = "zqmksspvmdfkcafdckad"

[functions.create-checkout]
verify_jwt = false

[functions.score-attempt]
verify_jwt = false

[functions.generate-exam]
verify_jwt = false

[functions.get-exam-review]
verify_jwt = false

[functions.admin-questions]
verify_jwt = false

[functions.admin-dashboard]
verify_jwt = false

[functions.admin-subscribers]
verify_jwt = false

[functions.admin-discounts]
verify_jwt = false

[functions.parse-pdf-questions]
verify_jwt = false
