ALTER TABLE profiles ADD COLUMN IF NOT EXISTS preferred_lang TEXT DEFAULT 'en';
ALTER TABLE attempts ADD COLUMN IF NOT EXISTS lang TEXT DEFAULT 'en';
ALTER TABLE attempts ADD COLUMN IF NOT EXISTS set_id TEXT DEFAULT 'SET_01';